### PR TITLE
fixed dark border around inactive window controls

### PR DESCRIPTION
**Pull request by zeparu**
https://github.com/mythio/macterial/issues/7

### CODE REVIEW

**Comment by zeparu** [comment]
oh i just noticed that my other commit i did after i created the pull request was also inside here, sorry this is my first pull request lol, im using dash to dock to customize the dash, and the theming of macterial interfered with the changes i did there, so i removed the dash assets

this only affects the little dot indicators for the dash as far as i can tell

if you dont want this / accepted that request by accident, you can revert the https://github.com/mythio/macterial/pull/14/commits/ecfb80e848c6b17f9f87720e3811c26f845b3852 commit

**Comment by ghost** [comment]
Oops! I didn't check what your commits did and merged them from the app lol. Will revert it soon! 

Cheers

**Comment by zeparu** [comment]
ya, revert the PR, ill create a new one

**Comment by ghost** [comment]
The PR is reverted.

**Pull request merged**
